config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reports do
    resources :tickets, only: [:create]
    resources :comments, only: [:new, :create]
    resources :follows, only: [:create]
  end

  get "close_ticket/:ticket_id", to: "tickets#close_ticket", as: :close_ticket

  resources :follows, only: [:destroy]
  get "dashboard", to: "users#dashboard"
  get "journal", to: "pages#journal"
  # get "myreports", to: "users#reports"
  # get "mytickets", to: "users#tickets"

  resources :tickets, only: [:show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reports
  has_many :follows
  has_many :comments
  has_many :tickets
  has_one_attached :photo
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @tickets = Ticket.where(user: current_user)
    @follows = Follow.where(user: current_user)
    @reports = Report.where(user: current_user)
  end
end

app/views/users/dashboard.html.erb
<div class="container">

  <div class="dash-info my-3">
    <div class="d-flex">
      <%= cl_image_tag current_user.photo.key, class: "avatar-dashboard", alt: "avatar image" %>
      <% if current_user.tickets.where(status: "Done").present? %>
        <p class="ms-3"><strong>Neighbourhood champion!</strong><br>You have completed <strong> <%= pluralize(current_user.tickets.where(status: "Done").count, "ticket") %></strong></p>
      <% end %>
    </div>
    <div class="col" id="dash-details">
      <h1><%= current_user.name %></h1>
      <div class="d-flex align-items-center">
        <h2 class=""><i class="fa-sharp fa-solid fa-location-arrow" style=""></i>  <%= current_user.neighbourhood %></h2>
      </div>
    </div>
  </div>

  <button type="button" class="dash-collapse">My Reports</button>
  <div class="dash-content">
    <div class="mt-3"></div>
    <% current_user.reports.each do |report| %>
      <div class="no-underline">
        <%= link_to report_path(report) do %>
          <div class="dash-report mb-3">
            <% report.photos.each do |photo| %>
              <%= cl_image_tag photo.key, class: 'img' %>
            <% end %>
            <div class="dash-report-infos">
              <h2><%= report.title %></h2>
              <p><%= report.description %></p>
              <div class="d-flex col-auto">
                <p class="justify-content-begin col"><strong><%= report.status %></strong></p>
                <p class="justify-content-end col"><strong>Votes: <%= report.votes %></strong></p>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

  <button type="button" class="dash-collapse">Followed Reports</button>

  <div class="dash-content">
    <div class="mt-3"></div>
    <% current_user.follows.each do |follow| %>
      <div class="no-underline">
        <%= link_to report_path(follow.report) do %>
          <div class="dash-report mb-3">
            <% follow.report.photos.each do |photo| %>
              <%= cl_image_tag photo.key, class: 'img' %>
            <% end %>
            <div class="dash-report-infos">
              <h2><%= follow.report.title %></h2>
              <p><%= follow.report.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    <%end%>
  </div>

<button type="button" class="dash-collapse">My Completed Tickets</button>
  <div class="dash-content">
    <div class="mt-3"></div>
    <% current_user.tickets.where(status: "Done").each do |ticket| %>
      <div class="no-underline">
        <%= link_to ticket_path(ticket) do %>
          <div class="dash-report mb-3">
            <% ticket.report.photos.each do |photo| %>
              <%= cl_image_tag photo.key, class: 'img' %>
            <% end %>
            <div class="dash-report-infos">
              <h2><%= ticket.report.title %></h2>
              <p><%= ticket.report.description %></p>
            </div>
          </div>
        <% end %>
      </div>
    <%end%>
  </div>

</div>

<script>
var coll = document.getElementsByClassName("dash-collapse");
var i;

for (i = 0; i < coll.length; i++) {
  coll[i].addEventListener("click", function() {
    this.classList.toggle("active");
    var content = this.nextElementSibling;
    if (content.style.maxHeight){
      content.style.maxHeight = null;
    } else {
      content.style.maxHeight = content.scrollHeight + "px";
    }
  });
}
</script>