config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reports do
    resources :tickets, only: [:create]
    resources :comments, only: [:new, :create]
    resources :follows, only: [:create]
  end

  get "close_ticket/:ticket_id", to: "tickets#close_ticket", as: :close_ticket

  resources :follows, only: [:destroy]
  get "dashboard", to: "users#dashboard"
  get "journal", to: "pages#journal"
  # get "myreports", to: "users#reports"
  # get "mytickets", to: "users#tickets"

  resources :tickets, only: [:show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reports
  has_many :follows
  has_many :comments
  has_many :tickets
  has_one_attached :photo
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show m-1 rounded-pill" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-primary alert-dismissible fade show m-1 rounded-pill" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "/reports", class: "navbar-brand" do %>
      <h1 class="neighbourhood-logo">OurNeighbourhood</h1>
    <% end %>

    <button class="navbar-toggler custom-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <% if user_signed_in? %>
        <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
        </a>
      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link" %>
      <% end %>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Dashboard - #{current_user.name}", "/dashboard", class: "dropdown-item" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </li>
        <% else %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar_footer.erb
 <div class="navbar-footer">
      <%= link_to "/reports", :class => current_page?("/reports") ? 'current' : '' do %>
        <div class="footer-button">
          <i class="fa-regular fa-map"></i>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <% if current_user.ticket_ids.last.present? %>
          <%= link_to "/tickets/#{current_user.ticket_ids.last}", :class => current_page?("/tickets/#{current_user.ticket_ids.last}") ? 'current' : '' do %>
            <div class="footer-button">
              <i class="fa-regular fa-circle-check"></i>
              <%# raise %>
            </div>
          <% end %>
          <% else %>
          <%= link_to "/reports" do %>
            <div class="footer-button">
                <i class="fa-regular fa-circle-check"></i>
                <%# raise %>
            </div>
          <% end %>
        <% end %>
      <% end %>
      <%# <div class="new-report-button-outline"></div> %>
      <%= link_to new_report_path, :class => current_page?(new_report_path) ? 'current' : '' do %>
        <div class="footer-button new-report-button">
          <i class="fa-solid fa-plus"></i>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <%= link_to "/dashboard", :class => current_page?("/dashboard") ? 'current' : '' do %>
          <div class="footer-button">
            <i class="fa-regular fa-circle-user"></i>
          </div>
        <% end %>
      <% end %>

      <div class="btn-group dropup">
        <% if user_signed_in? %>
          <button type="button" class="btn dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <div class="footer-button">
              <%= cl_image_tag current_user.photo.key, class: "avatar-navbar-footer" %>
            </div>
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Edit profile</a></li>
            <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
          </ul>
        <% else %>
          <%= link_to "Login", new_user_session_path, :class => current_page?(new_user_session_path) ? 'current' : '' %>
        <% end %>
      </div>

</div>