config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reports do
    resources :tickets, only: [:create]
    resources :comments, only: [:new, :create]
    resources :follows, only: [:create]
  end

  get "close_ticket/:ticket_id", to: "tickets#close_ticket", as: :close_ticket

  resources :follows, only: [:destroy]
  get "dashboard", to: "users#dashboard"
  get "journal", to: "pages#journal"
  # get "myreports", to: "users#reports"
  # get "mytickets", to: "users#tickets"

  resources :tickets, only: [:show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]
end

app/views/pages/_report_card.erb
  <% @reports_active.each do |report| %>
    <div class="no-underline">
      <%= link_to report_path(report) do %>
        <div class="card-report mb-4">
          <% report.photos.each do |photo| %>
            <%= cl_image_tag photo.key, class: 'img' %>
          <% end %>
          <div class="card-report-infos">
            <div class="report-div-userinfo">
              <p id="submit-p"><strong>By: <%= report.user.name %></strong></p>
              <%= cl_image_tag report.user.photo.key, class: "avatar-report-card" %>
              <%# raise %>
            </div>
            <div class="report-card-content">
              <h2><%= report.title %></h2>
              <p><%= report.description %></p>
              <div class="d-flex col-auto">
                <p class="justify-content-end col"><i class="fa-regular fa-bookmark primary"></i> <strong>Followers: <%= report.follows.count %></strong></p>
                <p class="justify-content-begin col"><strong><%= report.status %></strong></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/pages/home.html.erb
<div class="homepage">
  <div class="container">

    <div class="d-flex justify-content-end">
      <% if user_signed_in? %>
        <%= link_to "#{current_user.name}", reports_path , class: "" %>
      <% else  %>
        <%= link_to "Login", new_user_session_path , class: "btn btn-outline-primary btn-sm mt-3 ms-3 mb-3 rounded-pill" %>
      <% end %>
    </div>

    <div>
      <div class="d-flex justify-content-center">

        <div class="d-flex flex-column align-items-center text-justify">

          <div class="content">
            <div class="content__container">
              <h1 class="our-logo mb-3 mt-3">OurNeighbourhood</h1>
            </div>
          </div>
          <div class="illustration">
            <%= image_tag("neighbourhood.svg", alt: "people making something great together") %>
          </div>

          <h2 class="text-center mb-5 intro-sentance">Let's make it <br>even better!</h2>

          <%= link_to "Improve our neighbourhood", new_report_path , class: "btn btn-lg btn-primary rounded-pill mb-5" %>

          <div class="home-card rounded-4">
            <h2 class="d-flex justify-content-center mt-2 mb-3"><i class="fa-solid fa-camera"></i></h2>
            <h3 class="text-center">Identify and Report</h3>
            <p class="text-center">Spot an opportunity? Snap a photo and upload it to our app. Let's work to make it right.</p>
          </div>
          <div class="home-card rounded-4">
            <h2 class="d-flex justify-content-center mt-2 mb-3"><i class="fa-solid fa-screwdriver-wrench"></i></h2>
            <h3 class="text-center">Collaborate and Fix</h3>
            <p class="text-center">Connect with your neighbours. Come together to fix and improve your neighbourhood.</p>
          </div>
          <div class="home-card rounded-4">
            <h2 class="d-flex justify-content-center mt-2 mb-3"><i class="fa-solid fa-lightbulb"></i></h2>
            <h3 class="text-center">Inspire and Build</h3>
            <p class="text-center">Ideas shape our world. Share a vision for your area. Let's make those ideas come to life.</p>
          </div>
        </div>

      </div>
    </div>

  </div>
</div>

app/views/pages/journal.html.erb
<div class="container">
  <h1 class="mt-5 mb-3 text-center extra-nice-text">Congratulations!</h1>
  <h2 class="text-center"><%= current_user.name %></h2>
  <div class="col-auto text-center my-5">
    <%= cl_image_tag current_user.photo.key, class: "avatar-winner", alt: "avatar image" %>
  </div>
  <div class="text-center" >
    <p class="celebrate-emoji">🎉</p>
  </div>
  <h2 class="text-center mb-5 ">Great job</h2>
  <h3 class="text-center my-5">Thank you for improving your neighbourhood by completing:</h3>
  <% @reports.each do |report| %>
    <div class="cards mt-3 mx-4">
    <%= link_to report_path(report) do %>
      <div class="card-category"  style="background-image: url(<%= report.photos.map { |photo| cl_image_path(photo.key) }.join(', ') %>)">
        <p><%= report.title %></p>
      </div>
      <% end %>
    </div>
  <% end %>
  <div class="col-auto text-center mt-5">
    <h4 class="text-center my-5">Keep it up! Let's pick another report!</h4>
    <%= link_to "See tasks", reports_path, class: "btn btn-primary rounded-pill btn-lg text-center" %>
  </div>
  <div style="height: 140px">
  </div>
</div>