config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :reports do
    resources :tickets, only: [:create]
    resources :comments, only: [:new, :create]
    resources :follows, only: [:create]
  end

  get "close_ticket/:ticket_id", to: "tickets#close_ticket", as: :close_ticket

  resources :follows, only: [:destroy]
  get "dashboard", to: "users#dashboard"
  get "journal", to: "pages#journal"
  # get "myreports", to: "users#reports"
  # get "mytickets", to: "users#tickets"

  resources :tickets, only: [:show, :update, :destroy] do
    resources :notes, only: [:new, :create]
  end

  resources :notes, only: [:destroy]
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  has_many :follows, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tickets, dependent: :destroy
  has_many_attached :photos
  validates :title, presence: true, length: { maximum: 25 }
  validates :description, presence: true, length: { maximum: 200 }
  # validates :location, presence: true
  validates :category, presence: true, inclusion: { in: ['Improvement', 'Repair'] }
  validates :votes, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  # validates :latitude, presence: true
  # validates :longitude, presence: true
  attribute :votes, :integer, default: 0

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    # @reports = Report.order(:location, )
    # @reports = Report.all

    user_coordinates = Geocoder.coordinates(current_user.address)

    @reports = Report.near(user_coordinates, 8_000_000, order: 'distance')

    @reports_active = @reports.where.not(status: "Done")
    distances = []

    @reports_active.each do |report|
      distances.push(Geocoder::Calculations.distance_between(user_coordinates, [report.latitude, report.longitude]))
    end

    @markers = @reports_active.geocoded.map do |report|
      {
        lat: report.latitude,
        lng: report.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { report: }),
        marker_html: render_to_string(partial: "marker", locals: { report: })
      }
    end
  end

  def show
    @report = Report.find(params[:id])
    @ticket = Ticket.new
    @comment = Comment.new
    @follow = Follow.where(user: current_user, report: @report).first
    @markers = [
      {
        lat: @report.latitude,
        lng: @report.longitude,
        marker_html: render_to_string(partial: "marker", locals: { report: @report })
      }
    ]
  end

  def new
    @report = Report.new
  end

  def create
    @report = Report.new(report_params)
    @report.user = current_user
    if @report.save
      redirect_to report_path(@report)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @report = Report.find(params[:id])
  end

  def update
    @report = Report.find(params[:id])
    @report.update(report_params)
    redirect_to report_path(@report)
  end

  def destroy
    @report = Report.find(params[:id])
    @report.tickets.destroy_all
    @report.destroy
    redirect_to reports_path, status: :see_other
  end

  def report_params
    params.require(:report).permit(:title, :description, :location, :latitude, :longitude, :category, :status, :votes,
                                   photos: [])
  end
end

app/views/reports/_info_window.html.erb
<div class="card-report-infos text-left">
  <h2 id="popup-header"><%= link_to report.title, report_path(report), style: "text-decoration: none;" %></h2>
  <p id="popup-text"><%=  report.description %></p>
</div>

app/views/reports/_marker.html.erb
<div class="map-icon">
  <% if report.status == "In Progress" && report.category == "Repair" %>
    <i class="fa-solid fa-screwdriver-wrench in-progress"></i>
  <% elsif report.status == "Unclaimed" && report.category == "Repair" %>
    <i class="fa-solid fa-screwdriver-wrench unclaimed"></i>
  <% elsif report.status == "In Progress" && report.category == "Improvement" %>
   <i class="fa-solid fa-lightbulb in-progress"></i>
  <% elsif report.status == "Unclaimed" && report.category == "Improvement" %>
   <i class="fa-solid fa-lightbulb unclaimed"></i>
  <% end %>
</div>

app/views/reports/edit.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">

    <div class="container">
      <%= simple_form_for [@report] do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :category %>
        <%= link_to "Delete",
            report_path(@report),
            data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
            class: "btn btn-outline-secondary rounded-pill btn-sm px-3"
        %>
        <%= f.submit "Update Report", class: "btn btn-primary rounded-pill btn-sm px-3" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<div class="container tabs" data-controller="toggle-map">

  <div class="tab-content" id="pills-tabContent">

    <ul class="nav nav-pills mb-3 w-100 my-2" id="pills-tab" role="tablist">
      <li class="nav-item w-50 p-1" role="presentation">
        <button class="nav-link w-100  active rounded-pill border border-primary" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Reports</button>
      </li>
      <li class="nav-item w-50 p-1 " role="presentation">
        <button class="nav-link w-100 rounded-pill border border-primary ml-3" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Map</button>
      </li>
    </ul>

    <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" tabindex="0">
      <%= render 'pages/report_card', report: @reports_active %>
    </div>
  </div>

</div>


<div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" tabindex="0">
  <div class="map-js" style="width: 100%; height: 100vh;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
</div>

app/views/reports/new.html.erb
<div class="container-contact100">
  <div class="wrap-contact100">
    <span class="contact100-form-title">Let's start improving!</span>
      <div class="form-container">
        <%= simple_form_for [@report], data: {controller: 'geolocation'} do |f| %>
          <%= f.input :photos, as: :file, label: 'Take a photo', :input_html=> { multiple: true, :style=> '', class: 'rounded-4'} %>
          <%= f.input :title, label: 'what is it?', placeholder: 'A small change please 💡', :input_html => {:style=> '', class: 'rounded-4'} %>
          <%= f.input :description, label: 'A short description', placeholder: 'Write a little about what you found 🚯 or your idea for improvement 🌈', :input_html => {:style=> '', class: 'rounded-4'}%>
          <%= f.hidden_field :location %>
          <%= f.hidden_field :latitude, data: { geolocation_target: "latitude" } %>
          <%= f.hidden_field :longitude, data: { geolocation_target: "longitude" } %>
          <%= f.input :category, collection: ["Improvement", "Repair"], default:["Improvement"] %>
          <%= f.submit "Submit Report", class: 'btn btn-primary rounded-pill btn-lg col-12 mt-5' %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div style="height: 80px;"></div>

app/views/reports/show.html.erb
<div>
  <% @report.photos.each do |photo| %>
    <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <%= cl_image_tag photo.key, class: "rs-img-size", crop: :fill %>
    </a>
  <% end %>
</div>


<div class="container mt-3">
  <div class="rs-votes row">
    <div class="col-6 d-flex justify-content-start mb-2">
      <% if @follow %>
      <%= link_to "Unfollow Report", follow_path(@follow), class: "btn btn-outline-primary rounded-pill btn-sm px-3 ", data: {turbo_method: :delete} %>
      <% else %>
      <%= simple_form_for [@report, Follow.new] do |f| %>
        <%= f.submit "Follow Report", class: "btn btn-outline-primary rounded-pill btn-sm px-3 " %>
      <% end %>
      <% end %>
    </div>
    <div class="col-6">
      <p class="rs-text-right"><%= pluralize(@report.follows.count, "follower") %></p>

    </div>
  </div>
  <h2 class="mt-2"><%= @report.title %></h2>
  <p><%= @report.description %></p>
  <div>
    <% if @report.tickets.count != 0 %>
      <div>
        <div class="activity-card">
          <div class="d-flex justify-content-begin">
            <h5>Progress</h5>
          </div>
          <div>
            <% @report.tickets.each do |ticket| %>
              <p><%= ticket.user.name %> started working on this <%= time_ago_in_words(ticket.created_at) %> ago</p>
              <% if ticket.status == "Done" %>
                <p><%= ticket.user.name %> finished this report</p>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% else %>
      <h3>No one has claimed this report yet!</h3>
    <% end %>
  </div>
  <br>
  <div>
    <% if @report.tickets.present? %>
      <h4>Progress updates</h4>
      <% @report.tickets.each do |ticket| %>
        <% if ticket.notes.present? %>
          <div class="no-underline">
            <div class="card-report mb-3">
              <% ticket.notes.each do |note| %>
                <% if note.photos.present? %>
                  <div class="ticket-img">
                    <% note.photos.each do |photo| %>
                      <%= cl_image_tag photo.key, class: 'img' %>
                    <% end %>
                  </div>
                <% end %>
                <div class="card-report-infos flex-grow">
                  <div>
                    <p id="submit-p"><strong>Posted <%= time_ago_in_words(note.created_at) %> ago by <%= note.ticket.user.name %></strong></p>
                  </div>
                  <p><%= note.description %></p>
                  <div id="delete-note-btn" class="d-flex justify-content-end align-items-end">
                    <%= link_to note_path(note), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } do %>
                      <i class="fa-solid fa-trash align-self-end btn mt-3 btn btn-outline-secondary rounded-pill btn-sm px-3" style="color: #0E0000"></i>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      <br>
    <% end %>
  </div>

  <br>
  <div>
    <div style="width: 100%; height: 200px;" class="mb-3" id="map-container"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    <p><strong>Report Type: </strong><%= @report.category %></p>
    <div class="row">
      <div class="col-6">
      <p><strong>Status: </strong><%= @report.status %></p>
      </div>
      <div class="col-6 d-flex justify-content-end">
        <% if !@report.tickets.map(&:user).include?(current_user) %>
          <%= simple_form_for [@report, @ticket] do |f| %>
            <%= f.submit "Claim report", class: "btn btn-primary rounded-pill px-3" %>
          <% end %>
          <% else %>
            <%= link_to "Unclaim Report",
              ticket_path(@report.tickets.first),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "btn btn-outline-secondary rounded-pill px-3"
            %>
        <% end %>
      </div>
    </div>
  </div>


  <% if @report.comments.count != 0 %>
    <br>
    <h4>Comments:</h1>
    <% @report.comments.each do |comment| %>
      <div class="rs-comment-box">
        <p><strong>User: <%= comment.user.name %></strong><br><%= comment.description %><br><%= comment.created_at.to_formatted_s(:short) %></p>
      </div>
    <% end %>
  <% end %>


  <%= simple_form_for [@report, @comment] do |f| %>
    <%= f.input :description, label: "Leave a comment", :input_html => {:style=> '', class: 'rounded-4'} %>
    <%= f.submit "Submit comment", class: "btn btn-outline-primary rounded-pill px-3 mb-3" %>
  <% end %>

  <%= link_to "Back", reports_path, class: "btn btn-outline-secondary rounded-pill px-3" %>
  <% if @report.user == current_user %>
  <%= link_to "Edit", edit_report_path(@report), class: "btn btn-outline-secondary rounded-pill px-3" %>
  <% end %>
</div>
<div class="footer-padding" style="height: 200px"></div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Photo</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= cl_image_tag @report.photos.first.key, class: "modal-img", crop: :fill %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>